regions_with_country = {
    "algeria": "Middle East and North Africa, MENA",
    "bahrain": "Middle East and North Africa, MENA",
    "egypt": "Middle East and North Africa, MENA",
    "iran": "Middle East and North Africa, MENA",
    "iraq": "Middle East and North Africa, MENA",
    "israel": "Middle East and North Africa, MENA",
    "jordan": "Middle East and North Africa, MENA",
    "kuwait": "Middle East and North Africa, MENA",
    "lebanon": "Middle East and North Africa, MENA",
    "libya": "Middle East and North Africa, MENA",
    "morocco": "Middle East and North Africa, MENA",
    "oman": "Middle East and North Africa, MENA",
    "qatar": "Middle East and North Africa, MENA",
    "saudi arabia": "Middle East and North Africa, MENA",
    "palestine": "Middle East and North Africa, MENA",
    "syria": "Middle East and North Africa, MENA",
    "tunisia": "Middle East and North Africa, MENA",
    "united arab emirates": "Middle East and North Africa, MENA",
    "yemen": "Middle East and North Africa, MENA",
    "afghanistan": "South Asia",
    "bangladesh": "South Asia",
    "bhutan": "South Asia",
    "india": "South Asia",
    "maldives": "South Asia",
    "nepal": "South Asia",
    "pakistan": "South Asia",
    "sri lanka": "South Asia",
    "brunei": "SouthEast Asia",
    "cambodia": "SouthEast Asia",
    "indonesia": "SouthEast Asia",
    "laos": "SouthEast Asia",
    "malaysia": "SouthEast Asia",
    "myanmar": "SouthEast Asia",
    "philippines": "SouthEast Asia",
    "singapore": "SouthEast Asia",
    "thailand": "SouthEast Asia",
    "timorleste": "SouthEast Asia",
    "vietnam": "SouthEast Asia",
}
