time_zones = {
    "american samoa": "Samoa Standard Time (ST)",
    "hawaii": "Hawaii-Aleutian Standard Time (HAT)",
    "aleutian islands": "Hawaii-Aleutian Standard Time (HAT)",
    "alaska": "Alaska Standard Time (AKT)",
    "california": "Pacific Standard Time (PT)",
    "nevada": "Pacific Standard Time (PT)",
    "oregon": "Pacific Standard Time (PT)",
    "washington": "Pacific Standard Time (PT)",
    "idaho": "Pacific Standard Time (PT)",
    "british columbia": "Pacific Standard Time (PT)",
    "colorado": "Mountain Standard Time (MT)",
    "montana": "Mountain Standard Time (MT)",
    "new mexico": "Mountain Standard Time (MT)",
    "utah": "Mountain Standard Time (MT)",
    "wyoming": "Mountain Standard Time (MT)",
    "arizona": "Mountain Standard Time (MT)",
    "alberta": "Mountain Standard Time (MT)",
    "texas": "Central Standard Time (CT)",
    "illinois": "Central Standard Time (CT)",
    "minnesota": "Central Standard Time (CT)",
    "wisconsin": "Central Standard Time (CT)",
    "missouri": "Central Standard Time (CT)",
    "kansas": "Central Standard Time (CT)",
    "louisiana": "Eastern Standard Time (ET)",
    "iowa": "Central Standard Time (CT)",
    "oklahoma": "Central Standard Time (CT)",
    "saskatchewan": "Central Standard Time (CT)",
    "manitoba": "Central Standard Time (CT)",
    "new york": "Eastern Standard Time (ET)",
    "florida": "Eastern Standard Time (ET)",
    "georgia": "Eastern Standard Time (ET)",
    "north carolina": "Eastern Standard Time (ET)",
    "ohio": "Eastern Standard Time (ET)",
    "michigan": "Eastern Standard Time (ET)",
    "pennsylvania": "Eastern Standard Time (ET)",
    "virginia": "Eastern Standard Time (ET)",
    "massachusetts": "Eastern Standard Time (ET)",
    "indiana": "Eastern Standard Time (ET)",
    "tennessee": "Eastern Standard Time (ET)",
    "maryland": "Eastern Standard Time (ET)",
    "new jersey": "Eastern Standard Time (ET)",
    "south carolina": "Eastern Standard Time (ET)",
    "alabama": "Eastern Standard Time (ET)",
    "connecticut": "Eastern Standard Time (ET)",
    "kentucky": "Eastern Standard Time (ET)",
    "new hampshire": "Eastern Standard Time (ET)",
    "mississippi": "Eastern Standard Time (ET)",
    "maine": "Eastern Standard Time (ET)",
    "rhode island": "Eastern Standard Time (ET)",
    "delaware": "Eastern Standard Time (ET)",
    "vermont": "Eastern Standard Time (ET)",
    "west virginia": "Eastern Standard Time (ET)",
    "district of columbia": "Eastern Standard Time (ET)",
    "ontario": "Eastern Standard Time (ET)",
    "quebec": "Eastern Standard Time (ET)",
    "puerto rico": "Atlantic Standard Time",
    "nova scotia": "Atlantic Standard Time",
    "new brunswick": "Atlantic Standard Time",
    "prince edward island": "Atlantic Standard Time",
    "newfoundland and labrador": "Atlantic Standard Time",
    "guam": "Chamorro Standard Time (ChT)",
    "wake island": "Wake Island Time Zone (WIT)",
}
